/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hexstr.h"
#include <stdio.h>
#include <time.h>

char **
to_hex_1_svc(int *argp, struct svc_req *rqstp)
{

	static char * result;


	result = (char *) malloc(sizeof(char)*50);
	sprintf(result, "%x", *argp);

	printf("Converted: %s\n", result);
	fflush(stdout);
	return(&result);
}
