/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hexstr.h"


void
hexstr_1( char* host )
{
	CLIENT *clnt;
	int number;
	printf("Enter a number:");
	scanf("%d",&number);
	char * *result_1;
	int  to_hex_1_arg = number;
	clnt = clnt_create(host, HEXSTR, HEXSTRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = to_hex_1(&to_hex_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	printf("Hex version: %s\n", *result_1);
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	hexstr_1( host );
}
