/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HEXSTR_H_RPCGEN
#define _HEXSTR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define HEXSTR ((rpc_uint)1)
#define HEXSTRVER ((rpc_uint)1)

#ifdef __cplusplus
#define to_hex ((rpc_uint)1)
extern "C" char ** to_hex_1(int *, CLIENT *);
extern "C" char ** to_hex_1_svc(int *, struct svc_req *);

#elif __STDC__
#define to_hex ((rpc_uint)1)
extern  char ** to_hex_1(int *, CLIENT *);
extern  char ** to_hex_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define to_hex ((rpc_uint)1)
extern  char ** to_hex_1();
extern  char ** to_hex_1_svc();
#endif /* Old Style C */

#endif /* !_HEXSTR_H_RPCGEN */
