/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hexoct.h"


void
hexoct_1( char* host )
{
	CLIENT *clnt;
	int number;
	printf("Enter a number: ");
	scanf("%d",&number);
	int  *result_1;
	int  tohex_1_arg = number;
	int  *result_2;
	int  tooct_1_arg = number;
	clnt = clnt_create(host, HEXOCT, HEXOCT_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = tohex_1(&tohex_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = tooct_1(&tooct_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );

}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	hexoct_1( host );
}
